title: Show text when the player is near an NPC
hero_image: images/banner.png
description: Show a Canvas with Text (and other UI objects) when the Player collides with an NPC or other GameObjects
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - 
    title: Show text when the player is near an NPC
